export const LOAD_TEMPLATES_PROGRESS = "LOAD_TEMPLATES_PROGRESS";
export const LOAD_TEMPLATES_SUCCESS = "LOAD_TEMPLATES_SUCCESS";
export const LOAD_TEMPLATES_FAILURE = "LOAD_TEMPLATES_FAILURE";

export const SUBMIT_MEME_PROGRESS = "SUBMIT_MEME_PROGRESS";
export const SUBMIT_MEME_SUCCESS = "SUBMIT_MEME_SUCCESS";
export const SUBMIT_MEME_FAILURE = "SUBMIT_MEME_FAILURE";

export const SET_RANDOM_TEMPLATE = "SET_RANDOM_TEMPLATE";
export const PHASE_CHANGE = "PHASE_CHANGE";

export const START_COOK = "START_COOK";
export const COOK_TIME_IS_UP = "COOK_TIME_IS_UP";

export const CLEAR_MEMES = "CLEAR_MEMES";
export const RECEIVED_MEMES = "RECEIVED_MEMES";
