export const LOAD_TEMPLATES_PROGRESS = "LOAD_TEMPLATES_PROGRESS";
export const LOAD_TEMPLATES_SUCCESS = "LOAD_TEMPLATES_SUCCESS";
export const LOAD_TEMPLATES_FAILURE = "LOAD_TEMPLATES_FAILURE";

export const SET_RANDOM_TEMPLATE = "SET_RANDOM_TEMPLATE";

export const CLEAR_MEMES = "CLEAR_MEMES";
