export const PROCESS_IMAGE_LOADING = "PROCESS_IMAGE_LOADING";
export const PROCESS_IMAGE_SUCCESS = "PROCESS_IMAGE_SUCCESS";
export const PROCESS_IMAGE_FAILURE = "PROCESS_IMAGE_FAILURE";

export const ADD_PLAYER = "ADD_PLAYER";
export const REMOVE_PLAYER = "REMOVE_PLAYER";

export const RECIEVE_REACTIONS = "RECIEVE_REACTIONS";
export const RECEIVED_MEMES = "RECEIVED_MEMES";

export const AGGREGATE_EMOJIS = "AGGREGATE_EMOJIS";
